name: Draft a new release
# Creates Draft releases with release notes populated from the description of a release PR you just merged
# This workflow doesn't deploy anything. If you need to run a deploy for your repo, check out the deploy-on-release template in this repo

on:
  pull_request:
    # If your project uses a different convention, you can change this.
    # Values that won't break this workflow begin with "release" or "releases" and either a '\' or '-' (eg, release-v* or releases/v*, release/v*)
    branches: 
      - releases/v*
    types: [ closed ]

jobs:
  draft:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    name: Create the Release on the destination branch
    steps:
      - uses: actions/checkout@v2
      - name: Parse the tag name out of the release branch
        id: version
        run: >
          echo "tag_name="$(git branch --show-current | grep -E "^release.?[\/-]" | sed -E "s/release.?[\/-]//")"" >> $GITHUB_OUTPUT
      - name: Create the release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag_name }}
          release_name: ${{ steps.version.outputs.tag_name }}
          body: ${{ github.event.pull_request.body }}
          commitish: ${{ github.event.pull_request.merge_commit_sha }}
          draft: true
      - uses: mshick/add-pr-comment@v1
        name: Link the Release to the PR
        with:
          message: A draft release has been created for this version. Find it here! ${{ steps.release.outputs.html_url }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false
